import 'dart:io';
import '../models/product_entry.dart';

// Simplified share service without share_plus dependency
// This provides mock sharing functionality until dependencies are resolved
class ShareService {
  /// 기록된 데이터를 Excel 파일로 공유 (모조 구현)
  static Future<void> shareInventoryData(List<ProductEntry> entries) async {
    try {
      if (entries.isEmpty) {
        throw Exception('공유할 데이터가 없습니다.');
      }

      // 모조 구현: 로그만 출력
      print('파일 공유 모조 구현: Excel 파일 공유');
      print('제목: 재고 조사 결과 - ${DateTime.now().toLocal().toString().substring(0, 10)}');
      print('내용: 재고 조사 결과입니다. (총 ${entries.length}개 항목)');
    } catch (e) {
      throw Exception('파일 공유 실패: ${e.toString()}');
    }
  }

  /// 단순 텍스트로 공유 (모조 구현)
  static Future<void> shareAsText(List<ProductEntry> entries) async {
    try {
      if (entries.isEmpty) {
        throw Exception('공유할 데이터가 없습니다.');
      }

      final StringBuffer buffer = StringBuffer();
      buffer.writeln('재고 조사 결과');
      buffer.writeln('날짜: ${DateTime.now().toLocal().toString().substring(0, 10)}');
      buffer.writeln('총 항목: ${entries.length}개');
      buffer.writeln('');

      for (int i = 0; i < entries.length; i++) {
        final entry = entries[i];
        buffer.writeln('${i + 1}. ${entry.productName}');
        buffer.writeln('   바코드: ${entry.barcode}');
        buffer.writeln('   수량: ${entry.quantity ?? 0}');
        if (entry.recordedAt != null) {
          buffer.writeln('   기록시간: ${entry.recordedAt!.toLocal().toString().substring(0, 19)}');
        }
        buffer.writeln('');
      }

      // 모조 구현: 로그만 출력
      print('텍스트 공유 모조 구현:');
      print('제목: 재고 조사 결과 - ${DateTime.now().toLocal().toString().substring(0, 10)}');
      print('내용:\n${buffer.toString()}');
    } catch (e) {
      throw Exception('텍스트 공유 실패: ${e.toString()}');
    }
  }

  /// CSV 형식으로 공유 (모조 구현)
  static Future<void> shareAsCSV(List<ProductEntry> entries) async {
    try {
      if (entries.isEmpty) {
        throw Exception('공유할 데이터가 없습니다.');
      }

      final StringBuffer csvBuffer = StringBuffer();

      // CSV 헤더
      csvBuffer.writeln('날짜,상품명,바코드,수량');

      // CSV 데이터
      for (final entry in entries) {
        final date = entry.recordedAt?.toLocal().toString().substring(0, 19) ?? '';
        csvBuffer.writeln('$date,"${entry.productName}","${entry.barcode}",${entry.quantity ?? 0}');
      }

      // 모조 구현: 로그만 출력
      print('CSV 공유 모조 구현:');
      print('제목: 재고 조사 결과 (CSV) - ${DateTime.now().toLocal().toString().substring(0, 10)}');
      print('CSV 데이터:\n${csvBuffer.toString()}');
    } catch (e) {
      throw Exception('CSV 공유 실패: ${e.toString()}');
    }
  }

  /// 요약 정보 공유 (모조 구현)
  static Future<void> shareSummary(List<ProductEntry> entries) async {
    try {
      final totalItems = entries.length;
      final recordedItems = entries.where((e) => e.quantity != null).length;
      final totalQuantity = entries
          .where((e) => e.quantity != null)
          .map((e) => e.quantity!)
          .fold(0, (sum, qty) => sum + qty);

      final summary = '''
재고 조사 요약

📅 조사 날짜: ${DateTime.now().toLocal().toString().substring(0, 10)}

📊 조사 결과:
• 총 상품 항목: $totalItems개
• 기록 완료: $recordedItems개
• 총 수량: $totalQuantity개

📈 완료율: ${totalItems > 0 ? (recordedItems / totalItems * 100).toStringAsFixed(1) : '0.0'}%

🏷️ 주요 상품:
${_getTopItems(entries)}

Generated by CigarCounter App
''';

      // 모조 구현: 로그만 출력
      print('요약 공유 모조 구현:');
      print(summary);
    } catch (e) {
      throw Exception('요약 공유 실패: ${e.toString()}');
    }
  }

  /// 상위 5개 상품 정보 생성
  static String _getTopItems(List<ProductEntry> entries) {
    final recordedEntries = entries.where((e) => e.quantity != null).toList();

    if (recordedEntries.isEmpty) {
      return '• 기록된 상품이 없습니다.';
    }

    // 수량 기준 정렬
    recordedEntries.sort((a, b) => (b.quantity ?? 0).compareTo(a.quantity ?? 0));

    final topItems = recordedEntries.take(5).toList();
    final StringBuffer buffer = StringBuffer();

    for (int i = 0; i < topItems.length; i++) {
      final entry = topItems[i];
      buffer.writeln('• ${entry.productName}: ${entry.quantity}개');
    }

    if (recordedEntries.length > 5) {
      buffer.writeln('• ... 외 ${recordedEntries.length - 5}개 상품');
    }

    return buffer.toString().trim();
  }

  /// 공유 가능 여부 확인 (모조 구현)
  static Future<bool> canShare() async {
    try {
      // 모조 구현: 항상 true 반환
      return true;
    } catch (e) {
      return false;
    }
  }

  /// 앱에서 파일 열기 (모조 구현)
  static Future<void> openFile(File file) async {
    try {
      // 모조 구현: 로그만 출력
      print('파일 열기 모조 구현: ${file.path}');
    } catch (e) {
      throw Exception('파일 열기 실패: ${e.toString()}');
    }
  }
}